// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupPolicy) DeepCopyInto(out *BackupPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupPolicy.
func (in *BackupPolicy) DeepCopy() *BackupPolicy {
	if in == nil {
		return nil
	}
	out := new(BackupPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupSource) DeepCopyInto(out *BackupSource) {
	*out = *in
	if in.Offsite != nil {
		in, out := &in.Offsite, &out.Offsite
		*out = new(OffsiteBackupSource)
		**out = **in
	}
	if in.Ceph != nil {
		in, out := &in.Ceph, &out.Ceph
		*out = new(CephBackupSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupSource.
func (in *BackupSource) DeepCopy() *BackupSource {
	if in == nil {
		return nil
	}
	out := new(BackupSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephBackupSource) DeepCopyInto(out *CephBackupSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephBackupSource.
func (in *CephBackupSource) DeepCopy() *CephBackupSource {
	if in == nil {
		return nil
	}
	out := new(CephBackupSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephRestoreSource) DeepCopyInto(out *CephRestoreSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephRestoreSource.
func (in *CephRestoreSource) DeepCopy() *CephRestoreSource {
	if in == nil {
		return nil
	}
	out := new(CephRestoreSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerRevision) DeepCopyInto(out *ControllerRevision) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Data.DeepCopyInto(&out.Data)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerRevision.
func (in *ControllerRevision) DeepCopy() *ControllerRevision {
	if in == nil {
		return nil
	}
	out := new(ControllerRevision)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControllerRevision) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerRevisionList) DeepCopyInto(out *ControllerRevisionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ControllerRevision, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerRevisionList.
func (in *ControllerRevisionList) DeepCopy() *ControllerRevisionList {
	if in == nil {
		return nil
	}
	out := new(ControllerRevisionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControllerRevisionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeletePhase) DeepCopyInto(out *DeletePhase) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeletePhase.
func (in *DeletePhase) DeepCopy() *DeletePhase {
	if in == nil {
		return nil
	}
	out := new(DeletePhase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeletePhase) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeletePhaseList) DeepCopyInto(out *DeletePhaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DeletePhase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeletePhaseList.
func (in *DeletePhaseList) DeepCopy() *DeletePhaseList {
	if in == nil {
		return nil
	}
	out := new(DeletePhaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeletePhaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeletePhaseSpec) DeepCopyInto(out *DeletePhaseSpec) {
	*out = *in
	in.PhaseSpec.DeepCopyInto(&out.PhaseSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeletePhaseSpec.
func (in *DeletePhaseSpec) DeepCopy() *DeletePhaseSpec {
	if in == nil {
		return nil
	}
	out := new(DeletePhaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeletePhaseStatus) DeepCopyInto(out *DeletePhaseStatus) {
	*out = *in
	in.PhaseStatus.DeepCopyInto(&out.PhaseStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeletePhaseStatus.
func (in *DeletePhaseStatus) DeepCopy() *DeletePhaseStatus {
	if in == nil {
		return nil
	}
	out := new(DeletePhaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowSource) DeepCopyInto(out *FlowSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowSource.
func (in *FlowSource) DeepCopy() *FlowSource {
	if in == nil {
		return nil
	}
	out := new(FlowSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InServicePolicy) DeepCopyInto(out *InServicePolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InServicePolicy.
func (in *InServicePolicy) DeepCopy() *InServicePolicy {
	if in == nil {
		return nil
	}
	out := new(InServicePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallPhase) DeepCopyInto(out *InstallPhase) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallPhase.
func (in *InstallPhase) DeepCopy() *InstallPhase {
	if in == nil {
		return nil
	}
	out := new(InstallPhase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InstallPhase) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallPhaseList) DeepCopyInto(out *InstallPhaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InstallPhase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallPhaseList.
func (in *InstallPhaseList) DeepCopy() *InstallPhaseList {
	if in == nil {
		return nil
	}
	out := new(InstallPhaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InstallPhaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallPhaseSpec) DeepCopyInto(out *InstallPhaseSpec) {
	*out = *in
	in.PhaseSpec.DeepCopyInto(&out.PhaseSpec)
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallPhaseSpec.
func (in *InstallPhaseSpec) DeepCopy() *InstallPhaseSpec {
	if in == nil {
		return nil
	}
	out := new(InstallPhaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallPhaseStatus) DeepCopyInto(out *InstallPhaseStatus) {
	*out = *in
	in.PhaseStatus.DeepCopyInto(&out.PhaseStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallPhaseStatus.
func (in *InstallPhaseStatus) DeepCopy() *InstallPhaseStatus {
	if in == nil {
		return nil
	}
	out := new(InstallPhaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesDependency) DeepCopyInto(out *KubernetesDependency) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesDependency.
func (in *KubernetesDependency) DeepCopy() *KubernetesDependency {
	if in == nil {
		return nil
	}
	out := new(KubernetesDependency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LcmResourceCondition) DeepCopyInto(out *LcmResourceCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LcmResourceCondition.
func (in *LcmResourceCondition) DeepCopy() *LcmResourceCondition {
	if in == nil {
		return nil
	}
	out := new(LcmResourceCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LcmResourceConditionListHelper) DeepCopyInto(out *LcmResourceConditionListHelper) {
	*out = *in
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LcmResourceCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LcmResourceConditionListHelper.
func (in *LcmResourceConditionListHelper) DeepCopy() *LcmResourceConditionListHelper {
	if in == nil {
		return nil
	}
	out := new(LcmResourceConditionListHelper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LifecycleFlow) DeepCopyInto(out *LifecycleFlow) {
	*out = *in
	if in.Main != nil {
		in, out := &in.Main, &out.Main
		*out = (*in).DeepCopy()
	}
	if in.Phases != nil {
		in, out := &in.Phases, &out.Phases
		*out = make(map[string]unstructured.Unstructured, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LifecycleFlow.
func (in *LifecycleFlow) DeepCopy() *LifecycleFlow {
	if in == nil {
		return nil
	}
	out := new(LifecycleFlow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OffsiteBackupSource) DeepCopyInto(out *OffsiteBackupSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OffsiteBackupSource.
func (in *OffsiteBackupSource) DeepCopy() *OffsiteBackupSource {
	if in == nil {
		return nil
	}
	out := new(OffsiteBackupSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OffsiteRestoreSource) DeepCopyInto(out *OffsiteRestoreSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OffsiteRestoreSource.
func (in *OffsiteRestoreSource) DeepCopy() *OffsiteRestoreSource {
	if in == nil {
		return nil
	}
	out := new(OffsiteRestoreSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenstackLcmStatus) DeepCopyInto(out *OpenstackLcmStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]LcmResourceCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenstackLcmStatus.
func (in *OpenstackLcmStatus) DeepCopy() *OpenstackLcmStatus {
	if in == nil {
		return nil
	}
	out := new(OpenstackLcmStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationalPhase) DeepCopyInto(out *OperationalPhase) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationalPhase.
func (in *OperationalPhase) DeepCopy() *OperationalPhase {
	if in == nil {
		return nil
	}
	out := new(OperationalPhase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OperationalPhase) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationalPhaseList) DeepCopyInto(out *OperationalPhaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OperationalPhase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationalPhaseList.
func (in *OperationalPhaseList) DeepCopy() *OperationalPhaseList {
	if in == nil {
		return nil
	}
	out := new(OperationalPhaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OperationalPhaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationalPhaseSpec) DeepCopyInto(out *OperationalPhaseSpec) {
	*out = *in
	in.PhaseSpec.DeepCopyInto(&out.PhaseSpec)
	if in.InServicePolicy != nil {
		in, out := &in.InServicePolicy, &out.InServicePolicy
		*out = new(InServicePolicy)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationalPhaseSpec.
func (in *OperationalPhaseSpec) DeepCopy() *OperationalPhaseSpec {
	if in == nil {
		return nil
	}
	out := new(OperationalPhaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationalPhaseStatus) DeepCopyInto(out *OperationalPhaseStatus) {
	*out = *in
	in.PhaseStatus.DeepCopyInto(&out.PhaseStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationalPhaseStatus.
func (in *OperationalPhaseStatus) DeepCopy() *OperationalPhaseStatus {
	if in == nil {
		return nil
	}
	out := new(OperationalPhaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Oslc) DeepCopyInto(out *Oslc) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Oslc.
func (in *Oslc) DeepCopy() *Oslc {
	if in == nil {
		return nil
	}
	out := new(Oslc)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Oslc) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OslcList) DeepCopyInto(out *OslcList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Oslc, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OslcList.
func (in *OslcList) DeepCopy() *OslcList {
	if in == nil {
		return nil
	}
	out := new(OslcList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OslcList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OslcSpec) DeepCopyInto(out *OslcSpec) {
	*out = *in
	out.Source = in.Source
	if in.RevisionHistoryLimit != nil {
		in, out := &in.RevisionHistoryLimit, &out.RevisionHistoryLimit
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OslcSpec.
func (in *OslcSpec) DeepCopy() *OslcSpec {
	if in == nil {
		return nil
	}
	out := new(OslcSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OslcStatus) DeepCopyInto(out *OslcStatus) {
	*out = *in
	in.OpenstackLcmStatus.DeepCopyInto(&out.OpenstackLcmStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OslcStatus.
func (in *OslcStatus) DeepCopy() *OslcStatus {
	if in == nil {
		return nil
	}
	out := new(OslcStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhaseSource) DeepCopyInto(out *PhaseSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhaseSource.
func (in *PhaseSource) DeepCopy() *PhaseSource {
	if in == nil {
		return nil
	}
	out := new(PhaseSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhaseSpec) DeepCopyInto(out *PhaseSpec) {
	*out = *in
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(PhaseSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhaseSpec.
func (in *PhaseSpec) DeepCopy() *PhaseSpec {
	if in == nil {
		return nil
	}
	out := new(PhaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhaseStatus) DeepCopyInto(out *PhaseStatus) {
	*out = *in
	in.OpenstackLcmStatus.DeepCopyInto(&out.OpenstackLcmStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhaseStatus.
func (in *PhaseStatus) DeepCopy() *PhaseStatus {
	if in == nil {
		return nil
	}
	out := new(PhaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlanningPhase) DeepCopyInto(out *PlanningPhase) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlanningPhase.
func (in *PlanningPhase) DeepCopy() *PlanningPhase {
	if in == nil {
		return nil
	}
	out := new(PlanningPhase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlanningPhase) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlanningPhaseList) DeepCopyInto(out *PlanningPhaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PlanningPhase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlanningPhaseList.
func (in *PlanningPhaseList) DeepCopy() *PlanningPhaseList {
	if in == nil {
		return nil
	}
	out := new(PlanningPhaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlanningPhaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlanningPhaseSpec) DeepCopyInto(out *PlanningPhaseSpec) {
	*out = *in
	in.PhaseSpec.DeepCopyInto(&out.PhaseSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlanningPhaseSpec.
func (in *PlanningPhaseSpec) DeepCopy() *PlanningPhaseSpec {
	if in == nil {
		return nil
	}
	out := new(PlanningPhaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlanningPhaseStatus) DeepCopyInto(out *PlanningPhaseStatus) {
	*out = *in
	in.PhaseStatus.DeepCopyInto(&out.PhaseStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlanningPhaseStatus.
func (in *PlanningPhaseStatus) DeepCopy() *PlanningPhaseStatus {
	if in == nil {
		return nil
	}
	out := new(PlanningPhaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreSource) DeepCopyInto(out *RestoreSource) {
	*out = *in
	if in.Offsite != nil {
		in, out := &in.Offsite, &out.Offsite
		*out = new(OffsiteRestoreSource)
		**out = **in
	}
	if in.Ceph != nil {
		in, out := &in.Ceph, &out.Ceph
		*out = new(CephRestoreSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreSource.
func (in *RestoreSource) DeepCopy() *RestoreSource {
	if in == nil {
		return nil
	}
	out := new(RestoreSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RollbackPhase) DeepCopyInto(out *RollbackPhase) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RollbackPhase.
func (in *RollbackPhase) DeepCopy() *RollbackPhase {
	if in == nil {
		return nil
	}
	out := new(RollbackPhase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RollbackPhase) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RollbackPhaseList) DeepCopyInto(out *RollbackPhaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RollbackPhase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RollbackPhaseList.
func (in *RollbackPhaseList) DeepCopy() *RollbackPhaseList {
	if in == nil {
		return nil
	}
	out := new(RollbackPhaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RollbackPhaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RollbackPhaseSpec) DeepCopyInto(out *RollbackPhaseSpec) {
	*out = *in
	in.PhaseSpec.DeepCopyInto(&out.PhaseSpec)
	in.RestoreSource.DeepCopyInto(&out.RestoreSource)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RollbackPhaseSpec.
func (in *RollbackPhaseSpec) DeepCopy() *RollbackPhaseSpec {
	if in == nil {
		return nil
	}
	out := new(RollbackPhaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RollbackPhaseStatus) DeepCopyInto(out *RollbackPhaseStatus) {
	*out = *in
	in.PhaseStatus.DeepCopyInto(&out.PhaseStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RollbackPhaseStatus.
func (in *RollbackPhaseStatus) DeepCopy() *RollbackPhaseStatus {
	if in == nil {
		return nil
	}
	out := new(RollbackPhaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubResourceList) DeepCopyInto(out *SubResourceList) {
	*out = *in
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]unstructured.Unstructured, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubResourceList.
func (in *SubResourceList) DeepCopy() *SubResourceList {
	if in == nil {
		return nil
	}
	out := new(SubResourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestPhase) DeepCopyInto(out *TestPhase) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestPhase.
func (in *TestPhase) DeepCopy() *TestPhase {
	if in == nil {
		return nil
	}
	out := new(TestPhase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TestPhase) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestPhaseList) DeepCopyInto(out *TestPhaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TestPhase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestPhaseList.
func (in *TestPhaseList) DeepCopy() *TestPhaseList {
	if in == nil {
		return nil
	}
	out := new(TestPhaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TestPhaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestPhaseSpec) DeepCopyInto(out *TestPhaseSpec) {
	*out = *in
	in.PhaseSpec.DeepCopyInto(&out.PhaseSpec)
	if in.TestStrategy != nil {
		in, out := &in.TestStrategy, &out.TestStrategy
		*out = new(TestStrategy)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestPhaseSpec.
func (in *TestPhaseSpec) DeepCopy() *TestPhaseSpec {
	if in == nil {
		return nil
	}
	out := new(TestPhaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestPhaseStatus) DeepCopyInto(out *TestPhaseStatus) {
	*out = *in
	in.PhaseStatus.DeepCopyInto(&out.PhaseStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestPhaseStatus.
func (in *TestPhaseStatus) DeepCopy() *TestPhaseStatus {
	if in == nil {
		return nil
	}
	out := new(TestPhaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestStrategy) DeepCopyInto(out *TestStrategy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestStrategy.
func (in *TestStrategy) DeepCopy() *TestStrategy {
	if in == nil {
		return nil
	}
	out := new(TestStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficDrainPhase) DeepCopyInto(out *TrafficDrainPhase) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficDrainPhase.
func (in *TrafficDrainPhase) DeepCopy() *TrafficDrainPhase {
	if in == nil {
		return nil
	}
	out := new(TrafficDrainPhase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TrafficDrainPhase) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficDrainPhaseList) DeepCopyInto(out *TrafficDrainPhaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TrafficDrainPhase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficDrainPhaseList.
func (in *TrafficDrainPhaseList) DeepCopy() *TrafficDrainPhaseList {
	if in == nil {
		return nil
	}
	out := new(TrafficDrainPhaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TrafficDrainPhaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficDrainPhaseSpec) DeepCopyInto(out *TrafficDrainPhaseSpec) {
	*out = *in
	in.PhaseSpec.DeepCopyInto(&out.PhaseSpec)
	if in.TrafficDrainStrategy != nil {
		in, out := &in.TrafficDrainStrategy, &out.TrafficDrainStrategy
		*out = new(TrafficDrainStrategy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficDrainPhaseSpec.
func (in *TrafficDrainPhaseSpec) DeepCopy() *TrafficDrainPhaseSpec {
	if in == nil {
		return nil
	}
	out := new(TrafficDrainPhaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficDrainPhaseStatus) DeepCopyInto(out *TrafficDrainPhaseStatus) {
	*out = *in
	in.PhaseStatus.DeepCopyInto(&out.PhaseStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficDrainPhaseStatus.
func (in *TrafficDrainPhaseStatus) DeepCopy() *TrafficDrainPhaseStatus {
	if in == nil {
		return nil
	}
	out := new(TrafficDrainPhaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficDrainStrategy) DeepCopyInto(out *TrafficDrainStrategy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficDrainStrategy.
func (in *TrafficDrainStrategy) DeepCopy() *TrafficDrainStrategy {
	if in == nil {
		return nil
	}
	out := new(TrafficDrainStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficRolloutPhase) DeepCopyInto(out *TrafficRolloutPhase) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficRolloutPhase.
func (in *TrafficRolloutPhase) DeepCopy() *TrafficRolloutPhase {
	if in == nil {
		return nil
	}
	out := new(TrafficRolloutPhase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TrafficRolloutPhase) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficRolloutPhaseList) DeepCopyInto(out *TrafficRolloutPhaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TrafficRolloutPhase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficRolloutPhaseList.
func (in *TrafficRolloutPhaseList) DeepCopy() *TrafficRolloutPhaseList {
	if in == nil {
		return nil
	}
	out := new(TrafficRolloutPhaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TrafficRolloutPhaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficRolloutPhaseSpec) DeepCopyInto(out *TrafficRolloutPhaseSpec) {
	*out = *in
	in.PhaseSpec.DeepCopyInto(&out.PhaseSpec)
	if in.TrafficRolloutStrategy != nil {
		in, out := &in.TrafficRolloutStrategy, &out.TrafficRolloutStrategy
		*out = new(TrafficRolloutStrategy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficRolloutPhaseSpec.
func (in *TrafficRolloutPhaseSpec) DeepCopy() *TrafficRolloutPhaseSpec {
	if in == nil {
		return nil
	}
	out := new(TrafficRolloutPhaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficRolloutPhaseStatus) DeepCopyInto(out *TrafficRolloutPhaseStatus) {
	*out = *in
	in.PhaseStatus.DeepCopyInto(&out.PhaseStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficRolloutPhaseStatus.
func (in *TrafficRolloutPhaseStatus) DeepCopy() *TrafficRolloutPhaseStatus {
	if in == nil {
		return nil
	}
	out := new(TrafficRolloutPhaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficRolloutStrategy) DeepCopyInto(out *TrafficRolloutStrategy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficRolloutStrategy.
func (in *TrafficRolloutStrategy) DeepCopy() *TrafficRolloutStrategy {
	if in == nil {
		return nil
	}
	out := new(TrafficRolloutStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradePhase) DeepCopyInto(out *UpgradePhase) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradePhase.
func (in *UpgradePhase) DeepCopy() *UpgradePhase {
	if in == nil {
		return nil
	}
	out := new(UpgradePhase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UpgradePhase) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradePhaseList) DeepCopyInto(out *UpgradePhaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UpgradePhase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradePhaseList.
func (in *UpgradePhaseList) DeepCopy() *UpgradePhaseList {
	if in == nil {
		return nil
	}
	out := new(UpgradePhaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UpgradePhaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradePhaseSpec) DeepCopyInto(out *UpgradePhaseSpec) {
	*out = *in
	in.PhaseSpec.DeepCopyInto(&out.PhaseSpec)
	if in.BackupPolicy != nil {
		in, out := &in.BackupPolicy, &out.BackupPolicy
		*out = new(BackupPolicy)
		**out = **in
	}
	in.BackupSource.DeepCopyInto(&out.BackupSource)
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradePhaseSpec.
func (in *UpgradePhaseSpec) DeepCopy() *UpgradePhaseSpec {
	if in == nil {
		return nil
	}
	out := new(UpgradePhaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradePhaseStatus) DeepCopyInto(out *UpgradePhaseStatus) {
	*out = *in
	in.PhaseStatus.DeepCopyInto(&out.PhaseStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradePhaseStatus.
func (in *UpgradePhaseStatus) DeepCopy() *UpgradePhaseStatus {
	if in == nil {
		return nil
	}
	out := new(UpgradePhaseStatus)
	in.DeepCopyInto(out)
	return out
}
